CREATE DATABASE QLPHONGTRO;
GO

USE QLPHONGTRO;
GO


/* ========         BẢNG NHANVIEN  ====*/
CREATE TABLE NHANVIEN (
    MANV INT IDENTITY(1,1) PRIMARY KEY,
    HONV NVARCHAR(50) NOT NULL,
    TENNV NVARCHAR(20) NOT NULL,
    SDT VARCHAR(15) UNIQUE,
    EMAIL VARCHAR(100) UNIQUE,
    CHUCVU NVARCHAR(50) NOT NULL
);
GO

/* ========         BẢNG KHUVUC  ====*/
CREATE TABLE KHUVUC (
    MAKV VARCHAR(5) PRIMARY KEY,
    TENKV NVARCHAR(100) NOT NULL,
    DCHI NVARCHAR(100) NOT NULL,
    MANV INT,

    CONSTRAINT FK_KHUVUC_NHANVIEN FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)
);
GO

/* ========         BẢNG PHONG  ====*/
CREATE TABLE PHONG (
    MAPHONG INT IDENTITY(1,1) PRIMARY KEY,
    TENPHONG NVARCHAR(50) NOT NULL,
    MAKV VARCHAR(5) NOT NULL,

    GIAPHONG DECIMAL(18,2) NOT NULL
        CHECK (GIAPHONG > 0),

    DIENTICH FLOAT
        CHECK (DIENTICH > 0),

    LOAIPHONG NVARCHAR(50) NOT NULL,

    TRANGTHAIPHONG NVARCHAR(50) NOT NULL
        CHECK (TRANGTHAIPHONG IN
        (N'Còn trống', N'Đã thuê', N'Cần ở ghép')),

    SONGUOIHIENTAI INT NOT NULL DEFAULT 0
        CHECK (SONGUOIHIENTAI >= 0),

    NOITHAT NVARCHAR(200),

    CONSTRAINT FK_PHONG_KHUVUC FOREIGN KEY (MAKV) REFERENCES KHUVUC(MAKV)
);
GO

/* ========         BẢNG KHACHTHUE  ====*/
CREATE TABLE KHACHTHUE (
    MAKH INT IDENTITY(1,1) PRIMARY KEY,

    HOKH NVARCHAR(50) NOT NULL,
    TENKH NVARCHAR(20) NOT NULL,

    NGAYSINH DATE,

    GIOITINH NVARCHAR(10)
        CHECK (GIOITINH IN (N'Nam', N'Nữ', N'Khác')),

    CCCD VARCHAR(12) NOT NULL UNIQUE,

    SDT VARCHAR(15) NOT NULL UNIQUE,

    NGAYBATDAUTHUE DATETIME NOT NULL DEFAULT GETDATE(),

    TRANGTHAITHUE NVARCHAR(50) NOT NULL
        CHECK (TRANGTHAITHUE IN
        (N'Đang thuê', N'Đã trả phòng'))
);
GO

/* ========         BẢNG TAIKHOAN  ====*/
CREATE TABLE TAIKHOAN (
    MATK VARCHAR(5) PRIMARY KEY,

    MANV INT NULL,
    MAKH INT NULL,

    TENDANGNHAP NVARCHAR(70) NOT NULL UNIQUE,

    MATKHAU VARCHAR(20) NOT NULL,

    LOAITK CHAR(2) NOT NULL
        CHECK (LOAITK IN ('NV', 'KH')),

    CONSTRAINT FK_TAIKHOAN_NHANVIEN FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV),

    CONSTRAINT FK_TAIKHOAN_KHACH FOREIGN KEY (MAKH) REFERENCES KHACHTHUE(MAKH),

    CONSTRAINT CK_TAIKHOAN_LOAI
        CHECK (
            (LOAITK = 'NV' AND MANV IS NOT NULL AND MAKH IS NULL)
            OR
            (LOAITK = 'KH' AND MAKH IS NOT NULL AND MANV IS NULL)
        )
);
GO

/* ========         BẢNG LICHHEN ====*/
CREATE TABLE LICHHEN (
    MALH INT IDENTITY(1,1) PRIMARY KEY,

    MAKH INT NOT NULL,
    MANV INT NOT NULL,
    MAPHONG INT NOT NULL,

    THOIGIANHEN DATETIME NOT NULL,

    TRANGTHAIHEN NVARCHAR(50) NOT NULL
        CHECK (TRANGTHAIHEN IN
        (N'Đã đặt', N'Đã hủy', N'Hoàn thành')),

    NOIDUNGHEN NVARCHAR(200),

    THOIGIANTAO DATETIME NOT NULL DEFAULT GETDATE(),

    THOIGIANCAPNHAT DATETIME,

    CONSTRAINT FK_LICHHEN_KHACH FOREIGN KEY (MAKH) REFERENCES KHACHTHUE(MAKH),

    CONSTRAINT FK_LICHHEN_NV FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV),

    CONSTRAINT FK_LICHHEN_PHONG FOREIGN KEY (MAPHONG) REFERENCES PHONG(MAPHONG)
);
GO

/* ========         BẢNG TINOGHEP  ====*/
CREATE TABLE TINOGHEP (
    MATINOG INT IDENTITY(1,1) PRIMARY KEY,

    MAPHONG INT NOT NULL,
    MAKH INT NOT NULL,

    SONGUOICAN INT NOT NULL
        CHECK (SONGUOICAN > 0),

    GIOITINH NVARCHAR(10) NOT NULL
        CHECK (GIOITINH IN (N'Nam', N'Nữ', N'Khác')),

    GIACHIA DECIMAL(18,2) NOT NULL
        CHECK (GIACHIA > 0),

    MOTA NVARCHAR(MAX) NOT NULL,

    TRANGTHAITIN NVARCHAR(20) NOT NULL
        CHECK (TRANGTHAITIN IN
        (N'Đang tìm', N'Đã đủ người', N'Đã đóng')),


    TRANGTHAIYEUCAU NVARCHAR(20) NOT NULL
        CHECK (TRANGTHAITIN IN
        (N'Chờ duyệt', N'Đã duyệt', N'Từ chối')),

    CONSTRAINT FK_TINOGHEP_PHONG FOREIGN KEY (MAPHONG) REFERENCES PHONG(MAPHONG),

    CONSTRAINT FK_TINOGHEP_KHACH FOREIGN KEY (MAKH) REFERENCES KHACHTHUE(MAKH)
);
GO

/* ========         BẢNG HOPDONG ====*/
CREATE TABLE HOPDONG (
    MAHOPDONG INT IDENTITY(1,1) PRIMARY KEY,

    MAPHONG INT NOT NULL,
    MAKH INT NOT NULL,

    NGAYKYHD DATETIME NOT NULL DEFAULT GETDATE(),

    NGAYKT DATETIME NOT NULL,

    TRANGTHAIHOPDONG NVARCHAR(50) NOT NULL
        CHECK (TRANGTHAIHOPDONG IN
        (N'Còn hiệu lực', N'Hết hiệu lực')),

    THONGTINHD NVARCHAR(200) NOT NULL,

    CONSTRAINT FK_HOPDONG_PHONG FOREIGN KEY (MAPHONG) REFERENCES PHONG(MAPHONG),

    CONSTRAINT FK_HOPDONG_KHACH FOREIGN KEY (MAKH) REFERENCES KHACHTHUE(MAKH)
);
GO

/* ========         BẢNG HOADON  ====*/
CREATE TABLE HOADON (
    MAHOADON INT IDENTITY(1,1) PRIMARY KEY,

    MAHOPDONG INT NOT NULL,

    NGAYLAP DATETIME NOT NULL DEFAULT GETDATE(),

    TIENNUOC DECIMAL(18,2) NOT NULL DEFAULT 0
        CHECK (TIENNUOC >= 0),

    TIENDIEN DECIMAL(18,2) NOT NULL DEFAULT 0
        CHECK (TIENDIEN >= 0),

    TIENPHATSINH DECIMAL(18,2) NOT NULL DEFAULT 0
        CHECK (TIENPHATSINH >= 0),

    TONGTIEN AS (TIENNUOC + TIENDIEN + TIENPHATSINH),

    TRANGTHAITT NVARCHAR(50) NOT NULL
        CHECK (TRANGTHAITT IN
        (N'Đã thanh toán', N'Chưa thanh toán')),

    NGAYTHANHTOAN DATETIME NULL,

    PHUONGTHUCTT NVARCHAR(50) NULL 
        CHECK (PHUONGTHUCTT IN (N'Tiền mặt', N'Chuyển khoản', N'Quét mã QR')),
    CONSTRAINT FK_HOADON_HD FOREIGN KEY (MAHOPDONG) REFERENCES HOPDONG(MAHOPDONG)
);
GO

/* ========         BẢNG BAOCAO  ====*/

CREATE TABLE BAOCAO (
    MABC INT IDENTITY(1,1) PRIMARY KEY,

    MANV INT NOT NULL,

    LOAIBC NVARCHAR(50) NOT NULL,

    NOIDUNGBC NVARCHAR(200) NOT NULL,

    THOIGIANBC DATETIME NOT NULL DEFAULT GETDATE(),

    CONSTRAINT FK_BAOCAO_NV FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)
);
GO
/* ========         BẢNG DANHGIA  ====*/
CREATE TABLE DANHGIA (
    MADG INT IDENTITY(1,1) PRIMARY KEY, 
    MANGUOIDG INT NOT NULL,           
    MANGUOIDUOCDG INT NOT NULL,        
    MAHOPDONG INT NOT NULL,           
    DIEM INT NOT NULL,                 
    NOIDUNG NVARCHAR(MAX),           
    THOIGIANDG DATETIME DEFAULT GETDATE(), 

    -- Ràng buộc kiểm tra điểm từ 1 đến 5
    CONSTRAINT CHK_DiemDanhGia CHECK (DIEM BETWEEN 1 AND 5),
    -- Ràng buộc không cho tự đánh giá chính mình
    CONSTRAINT CHK_KhongTuDanhGia CHECK (MaNguoiDG <> MANGUOIDG),
    -- Các khóa ngoại
    CONSTRAINT FK_DanhGia_NguoiGui FOREIGN KEY (MANGUOIDG) REFERENCES KHACHTHUE(MAKH),
    CONSTRAINT FK_DanhGia_NguoiNhan FOREIGN KEY (MANGUOIDUOCDG) REFERENCES KHACHTHUE(MAKH),
    CONSTRAINT FK_DanhGia_HopDong FOREIGN KEY (MAHOPDONG) REFERENCES HOPDONG(MAHOPDONG) 
);
GO